// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"EduKita/modules/auth/data/repositories"
	"EduKita/modules/auth/domain/usecases"
	"EduKita/modules/auth/handler"
	"database/sql"
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
)

// Injectors from auth_handler.go:

func InitializeAuthHandler(db *sql.DB) *handler.AuthHandler {
	userRepositoryImpl := repositories.NewUserRepository(db)
	loginUsecaseImpl := usecases.NewLoginUsecase(userRepositoryImpl)
	generateTokenUsecaseImpl := usecases.NewGenerateTokenUsecase()
	refreshTokenUsecaseImpl := usecases.NewRefreshTokenUsecase()
	getShortProfileUsecaseImpl := usecases.NewGetShortProfileUsecase(userRepositoryImpl)
	validate := NewValidator()
	authHandler := handler.NewAuthHandler(loginUsecaseImpl, generateTokenUsecaseImpl, refreshTokenUsecaseImpl, getShortProfileUsecaseImpl, validate)
	return authHandler
}

// auth_handler.go:

var AuthHandlerSet = wire.NewSet(repositories.NewUserRepository, wire.Bind(new(repositories.UserRepository), new(*repositories.UserRepositoryImpl)), usecases.NewLoginUsecase, wire.Bind(new(usecases.LoginUsecase), new(*usecases.LoginUsecaseImpl)), usecases.NewGenerateTokenUsecase, wire.Bind(new(usecases.GetShortProfileUsecase), new(*usecases.GetShortProfileUsecaseImpl)), usecases.NewGetShortProfileUsecase, wire.Bind(new(usecases.GenerateTokenUsecase), new(*usecases.GenerateTokenUsecaseImpl)), usecases.NewRefreshTokenUsecase, wire.Bind(new(usecases.RefreshTokenUsecase), new(*usecases.RefreshTokenUsecaseImpl)), NewValidator, handler.NewAuthHandler)

func NewValidator() *validator.Validate {
	return validator.New()
}
