// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"EduKita/modules/profile/data/repositories"
	"EduKita/modules/profile/domain/usecases"
	"EduKita/modules/profile/handler"
	"database/sql"
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
)

// Injectors from profile_handler.go:

func InitializeProfileHandler(db *sql.DB) *handler.ProfileHandler {
	profileRepositoryImpl := repositories.NewProfileRepository(db)
	getProfileUsecaseImpl := usecases.NewGetProfileUsecase(profileRepositoryImpl)
	validate := NewValidator()
	profileHandler := handler.NewProfileHandler(getProfileUsecaseImpl, validate)
	return profileHandler
}

// profile_handler.go:

func NewValidator() *validator.Validate {
	return validator.New()
}

var ProfileHandlerSet = wire.NewSet(repositories.NewProfileRepository, wire.Bind(new(repositories.ProfileRepository), new(*repositories.ProfileRepositoryImpl)), usecases.NewGetProfileUsecase, wire.Bind(new(usecases.GetProfileUsecase), new(*usecases.GetProfileUsecaseImpl)), NewValidator, handler.NewProfileHandler)
