version: "3"

services:
  edu-kita-app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
    networks:
      - nginx-proxy-network

networks:
  nginx-proxy-network:
    external: true
