CREATE TABLE IF NOT EXISTS users (
    id uuid PRIMARY KEY,
    firebase_id VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    profile_picture VARCHAR(1000),
    created_at BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP) * 1000,
    updated_at BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP) * 1000
);

CREATE INDEX IF NOT EXISTS idx_firebase_id ON users (firebase_id);
CREATE INDEX IF NOT EXISTS idx_email ON users (email);