version: '1.0'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: edu_kita
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - local_network

  edu_kita-local:
    image: edu_kita-local
    build:
      context: ../../
      dockerfile: docker/local/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - local_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - local_network

networks:
  local_network:
    driver: bridge
