// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"EduKita/modules/question/data/repositories"
	"EduKita/modules/question/domain/usecases"
	"EduKita/modules/question/handler"
	"database/sql"
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
)

// Injectors from question_handler.go:

func InitializeQuestionHandler(db *sql.DB) *handler.QuestionHandler {
	questionRepositoryImpl := repositories.NewQuestionRepository(db)
	getQuestionByLearningTopicUsecaseImpl := usecases.NewGetQuestionByLearningTopicUsecase(questionRepositoryImpl)
	validate := NewValidator()
	questionHandler := handler.NewQuestionHandler(getQuestionByLearningTopicUsecaseImpl, validate)
	return questionHandler
}

// question_handler.go:

var QuestionHandlerSet = wire.NewSet(repositories.NewQuestionRepository, wire.Bind(new(repositories.QuestionRepository), new(*repositories.QuestionRepositoryImpl)), usecases.NewGetQuestionByLearningTopicUsecase, wire.Bind(new(usecases.GetQuestionByLearningTopicUsecase), new(*usecases.GetQuestionByLearningTopicUsecaseImpl)), NewValidator, handler.NewQuestionHandler)

func NewValidator() *validator.Validate {
	return validator.New()
}
