// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"EduKita/modules/question/data/repositories"
	"EduKita/modules/question/domain/usecases"
	"EduKita/modules/question/handler"
	"database/sql"
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
)

// Injectors from answer_handler.go:

func InitializeAnswerHandler(db *sql.DB) *handler.AnswerHandler {
	answerRepositoryImpl := repositories.NewAnswerRepository(db)
	answerQuestionUsecaseImpl := usecases.NewAnswerQuestionUsecase(answerRepositoryImpl)
	validate := NewValidator()
	answerHandler := handler.NewAnswerHandler(answerQuestionUsecaseImpl, validate)
	return answerHandler
}

// Injectors from question_handler.go:

func InitializeQuestionHandler(db *sql.DB) *handler.QuestionHandler {
	questionRepositoryImpl := repositories.NewQuestionRepository(db)
	getQuestionByLearningTopicUsecaseImpl := usecases.NewGetQuestionByLearningTopicUsecase(questionRepositoryImpl)
	validate := NewValidator()
	questionHandler := handler.NewQuestionHandler(getQuestionByLearningTopicUsecaseImpl, validate)
	return questionHandler
}

// answer_handler.go:

var AnswerHandler = wire.NewSet(repositories.NewAnswerRepository, wire.Bind(new(repositories.AnswerRepository), new(*repositories.AnswerRepositoryImpl)), usecases.NewAnswerQuestionUsecase, wire.Bind(new(usecases.AnswerQuestionUsecase), new(*usecases.AnswerQuestionUsecaseImpl)), NewValidator, handler.NewAnswerHandler)

// question_handler.go:

var QuestionHandlerSet = wire.NewSet(repositories.NewQuestionRepository, wire.Bind(new(repositories.QuestionRepository), new(*repositories.QuestionRepositoryImpl)), usecases.NewGetQuestionByLearningTopicUsecase, wire.Bind(new(usecases.GetQuestionByLearningTopicUsecase), new(*usecases.GetQuestionByLearningTopicUsecaseImpl)), NewValidator, handler.NewQuestionHandler)

func NewValidator() *validator.Validate {
	return validator.New()
}
